services:
  mysql:
    image: mysql:8.0
    container_name: acpay-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acpay_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/acpay_db.sql:/docker-entrypoint-initdb.d/acpay_db.sql  # 自動載入 SQL 檔案
    networks:
      - acpay_network

  api:
    build: .
    container_name: acpay-api
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql+pymysql://acpay_user:acpay_pass@mysql:3307/acpay_db"
    ports:
      - "8000:8000"
    networks:
      - acpay_network

volumes:
  mysql_data:

networks:
  acpay_network:
