networks:
  app-network:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: acpay_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - ./mysql/acpay_db.sql:/docker-entrypoint-initdb.d/acpay_db.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - mysql
    networks:
      - app-network

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "mysql+pymysql://admin:admin@mysql:3306/acpay_db"
    depends_on:
      - mysql
    networks:
      - app-network

